version: "3"
services:
  frontend:
    image: frontend-production
    restart: unless-stopped
    stdin_open: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mern-app  
  backend:
    image: backend-production
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - mern-app
networks:
    mern-app:
      driver: bridge