version: "3"
services:
  frontend:
    image: frontend
    build: ./frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app  
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    image: backend
    build: ./backend/
    ports:
      - "4000:4000"
    networks:
      - mern-app
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
networks:
    mern-app:
      driver: bridge

